myhomework24/myhomework24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns +=[
        path('__debug__/', include(debug_toolbar.urls)),
    ]

myhomework24/shop/urls.py
from django.urls import path
from shop import views

app_name = "shop"

urlpatterns = [
    path("", views.shop_list, name = "shop_list"),
    path("<int:pk>/", views.shop_detail, name="shop_detail"),
    path("new/", views.shop_new, name="shop_new"),
    path("<int:pk>/edit/", views.shop_edit, name="shop_edit"),
    path("<int:pk>/delete/", views.shop_delete, name="shop_delete"),
]

myhomework24/shop/models.py
from django.core.validators import RegexValidator
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "카테고리"
        verbose_name_plural = "카테고리 목록"
        ordering =["-id"]


class Shop(TimestampedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    telephone = models.CharField(max_length=13,
                                 validators=[
                                     RegexValidator(r"^\d{2,3}-?\d{3,4}-?\d{3,4}$",
                                                     message = "전화번호를 입력해주세요."),
                                 ],
                                 help_text = "입력예) 042-1234-1234")
    tag_set = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "포스팅"
        verbose_name_plural = "포스팅 목록"
        ordering =["-id"]


class Tag(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "태그"
        verbose_name_plural = "태그 목록"
        ordering = ["name"]


class Review(TimestampedModel):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=20)
    message = models.TextField()

    class Meta:
        verbose_name = "댓글"
        verbose_name_plural = "댓글 목록"
        ordering =["-id"]

myhomework24/shop/forms.py
from django import forms
from shop.models import Shop


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = "__all__"

myhomework24/shop/views.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from shop.forms import ShopForm
from shop.models import Shop, Category


def shop_list(request: HttpRequest) -> HttpResponse:
    shop_qs = Shop.objects.all()
    return render(request, 'shop/shop_list.html', {
        'shop_list': shop_qs,
    })


def shop_detail(request: HttpRequest, pk: int) -> HttpResponse:
    shop = get_object_or_404(Shop, pk=pk)
    return render(request, "shop/shop_detail.html", {
        "shop": shop,
    },)


def shop_new(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ShopForm(request.POST, request.FILES)
        if form.is_valid():
            saved_shop = form.save()
            messages.success(request, "새로운 포스팅을 저장했습니다.")
            return redirect("shop:shop_detail", saved_shop.pk)
        else:
            form = ShopForm()

        return render(request, "shop/shop_form.html", {
            "form": form,
        })


def shop_edit(request: HttpRequest, pk: int) -> HttpResponse:
    shop = get_object_or_404(Shop, pk=pk)

    if request.method == "POST":
        form = ShopForm(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            saved_shop = form.save()
            messages.success(request, "포스팅을 수정했습니다.")
            return redirect("shop:shop_detail", saved_shop.pk)
        else:
            form = ShopForm(instance=shop)
        return render(request, "shop/shop_form.html", {
            "form": form,
            "shop": shop,
        })


def shop_delete(request: HttpRequest, pk: int) -> HttpResponse:
    raise NotImplementedError("삭제는 아직 구현하지 않았습니다...")

myhomework24/shop/templates/shop/layout.html
{% extends "layout.html" %}

{% block extra_head %}
    <style>
        body{
            background: #ffe8be;
        }
    </style>
{% endblock %}

myhomework24/shop/templates/shop/shop_detail.html
{% extends "shop/layout.html" %}

{#{% block content %}#}
{#    {{ block.super }} ::#}
{#    {{ shop.name }}#}
{#{% endblock %}#}
{% block content %}
    <h2>{{ shop.name }}</h2>

    <p>
    {% for tag in shop.tag_set.all %}
        {{ tag.name }}
    {% endfor %}
    </p>

    {{ shop.description }}

    {{ shop.content|linebreaks }}

    <hr>
    <a href="{% url "shop:shop_list" %}">
        포스팅 목록
    </a>

    <a href="{% url "shop:shop_edit" shop.pk %}">
        포스팅 수정
    </a>

    <a href="{% url "shop:shop_delete" shop.pk %}">
        포스팅 삭제
    </a>
{% endblock %}

myhomework24/shop/templates/shop/shop_form.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>Shop Form</h2>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit">
    </form>

    <hr>
    <a href="{% url "shop:shop_detail" shop.pk %}">
        조회화면으로
    </a>
{% endblock %}

myhomework24/shop/templates/shop/shop_list.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>Shop List</h2>

    <table>
        <thead>
        {% for shop in shop_list %}
        <tr>
            <td>
                <a href="{% url "shop:shop_detail" shop.pk %}">
                    {{ shop.name }}
                </a>
            </td>
        </tr>
        {% endfor %}
        </thead>
    </table>

    <hr>
    <a href="{% url "shop:shop_new" %}">
        포스팅 쓰기
    </a>

{% endblock %}