mydjango25/accounts/urls.py
from django.urls import path

from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

mydjango25/mydjango25/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shop.urls')),
    path('', TemplateView.as_view(template_name='root.html'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

mydjango25/shop/urls.py
from django.urls import path
from shop import views

app_name = "shop"

urlpatterns = [
    path("", views.shop_list, name="shop_list"),
    path("<int:pk>/", views.shop_detail, name="shop_detail"),
    path("<int:shop_pk>/reviews/new/", views.review_new, name="review_new"),
    path("<int:shop_pk>/reviews/<int:pk>/edit/", views.review_edit, name="review_edit"),
]

mydjango25/accounts/models.py
from django.db import models

# Create your models here.

mydjango25/shop/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "카테고리"
        verbose_name_plural = "카테고리 목록"


class Shop(TimestampedModel):
    # settings.AUTH_USER_MODEL 의 디폴트 값 : "auth.User"
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    photo = models.ImageField(upload_to="shop/shop/%Y/%m/%d", blank=True)
    tag_set = models.ManyToManyField('Tag', blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:shop_detail", args=[self.pk])

    class Meta:
        ordering = ["-id"]
        verbose_name = "상점"
        verbose_name_plural = "상점 목록"


class Review(TimestampedModel):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-id"]
        verbose_name = "리뷰"
        verbose_name_plural = "리뷰 목록"


class Tag(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "태그"
        verbose_name_plural = "태그 목록"

mydjango25/shop/templates/shop/forms.py
from django import forms

from shop.models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["message"]

mydjango25/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

signup = CreateView.as_view(
    form_class=UserCreationForm,
    success_url=reverse_lazy("accounts:login"),
    template_name="accounts/signup_form.html",
)


login = LoginView.as_view(
    template_name="accounts/login_form.html",
)


# TODO: 커스텀 CBV를 만든다면, LoginRequiredMixin를 상속받도록 할 수 있습니다.
profile = login_required(
    TemplateView.as_view(
        template_name="accounts/profile_form.html",
    )
)


logout = LogoutView.as_view(
    # next_page="accounts:login",
    next_page="root",
)

mydjango25/shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404, resolve_url
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from shop.mixins import ReviewUserCheckMixin
from shop.models import Shop, Category, Review
from shop.templates.shop.forms import ReviewForm


class ShopListView(ListView):
    model = Shop
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["category_list"] = Category.objects.all()
        return context_data


shop_list = ShopListView.as_view()

shop_detail = DetailView.as_view(
    model=Shop,
)


class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    # success_url = reverse_lazy("shop:shop_list")

    # 유효성 검사에 통과한다면...
    def form_valid(self, form) -> HttpResponse:
        # self.kwargs : URL Captured 값들이 사전으로 저장
        shop_pk = self.kwargs["shop_pk"]
        shop = get_object_or_404(Shop, pk=shop_pk)

        review = form.save(commit=False)
        review.shop = shop
        review.user = self.request.user
        review.save()
        return redirect(shop)


review_new = ReviewCreateView.as_view()


class ReviewUpdateView(LoginRequiredMixin, ReviewUserCheckMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    # success_url = reverse_lazy("shop:shop_list")

    def get_success_url(self) -> str:
        review = self.object
        return resolve_url(review.shop)

    # def test_func(self):
    #     review = self.get_object()
    #     return self.request.user == review.user


review_edit = ReviewUpdateView.as_view()

mydjango25/shop/templates/shop/layout.html
{% extends "layout.html" %}

mydjango25/shop/templates/shop/review_form.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>Review Form</h2>

    {% include "_form.html" with submit_label="리뷰 저장" %}
{% endblock %}

mydjango25/shop/templates/shop/shop_detail.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>{{ shop.name }}</h2>

    <p>
        {% for tag in shop.tag_set.all %}
            {{ tag.name }}
        {% empty %}
            등록된 태그가 없습니다.
        {% endfor %}
    </p>

    {% if shop.photo %}
        <img src="{{ shop.photo.url }}" alt="{{ shop.name }}">
    {% endif %}

    {{ shop.description|default:"설명이 없습니다." }}

    <hr>
    <h3>리뷰</h3>

    <a href="{% url 'shop:review_new' shop.pk %}" class="btn btn-primary">리뷰쓰기</a>

    {% for review in shop.review_set.all %}
        <div>
            {{ review.message }}
            by {{ review.user }}
            at {{ review.created_at }}
            {% if review.user == request.user %}
                <a href="{% url 'shop:review_edit' shop.pk review.pk %}">Edit</a>
            {% endif %}
        </div>
    {% empty %}
        등록된 리뷰가 없습니다.
    {% endfor %}
{% endblock %}

mydjango25/shop/templates/shop/shop_list.html
{% extends "shop/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <p>
        {% for category in category_list %}
            <span class="badge bg-info">
                {{ category.name }}
            </span>
        {% endfor %}
    </p>

    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>상점명</th>
            <th>등록일시</th>
        </tr>
        </thead>
        <tbody>
        {% for shop in shop_list %}
            <tr>
                <td>
                    <a href="{% url 'shop:shop_detail' shop.pk %}">
                        {{ shop.name }}
                    </a>
                </td>
                <td>
                    {{ shop.created_at }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% bootstrap_pagination page_obj %}
{% endblock %}